Error: Invalid data source
│ 
│   on test.tf line 28, in data "aws_subnet_ids" "public_subnets_vpc1":
│   28: data "aws_subnet_ids" "public_subnets_vpc1" {
│ 
│ The provider hashicorp/aws does not support data source "aws_subnet_ids".
╵
╷
│ Error: Invalid data source
│ 
│   on test.tf line 32, in data "aws_subnet_ids" "public_subnets_vpc2":
│   32: data "aws_subnet_ids" "public_subnets_vpc2" {
│ 
│ The provider hashicorp/aws does not support data source "aws_subnet_ids".
