│ Error: Invalid data source
│ 
│   on test.tf line 16, in data "aws_subnet_ids" "public_subnets_vpc1":
│   16: data "aws_subnet_ids" "public_subnets_vpc1" {
│ 
│ The provider hashicorp/aws does not support data source "aws_subnet_ids".
╵
╷
│ Error: Invalid data source
│ 
│   on test.tf line 26, in data "aws_subnet_ids" "public_subnets_vpc2":
│   26: data "aws_subnet_ids" "public_subnets_vpc2" {
│ 
│ The provider hashicorp/aws does not support data source "aws_subnet_ids".
